"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WechatWebInstance = exports.WechatPublicInstance = exports.WechatMpInstance = exports.AmapSDK = exports.WechatSDK = void 0;
var tslib_1 = require("tslib");
var WechatSDK_1 = tslib_1.__importStar(require("./WechatSDK"));
exports.WechatSDK = WechatSDK_1.default;
Object.defineProperty(exports, "WechatMpInstance", { enumerable: true, get: function () { return WechatSDK_1.WechatMpInstance; } });
Object.defineProperty(exports, "WechatPublicInstance", { enumerable: true, get: function () { return WechatSDK_1.WechatPublicInstance; } });
Object.defineProperty(exports, "WechatWebInstance", { enumerable: true, get: function () { return WechatSDK_1.WechatWebInstance; } });
var AmapSDK_1 = tslib_1.__importDefault(require("./AmapSDK"));
exports.AmapSDK = AmapSDK_1.default;
tslib_1.__exportStar(require("./service/amap/Amap"), exports);
